<?php

declare (strict_types = 1);

/**
 * @file
 * Contains hook implementations for the Processed Audio Entity module.
 */

use Drupal\processed_audio_entity\Entity\ProcessedAudio;

/**
 * Implements hook_entity_bundle_info_alter.
 */
function processed_audio_entity_entity_bundle_info_alter(array &$bundles) : void {
  if (!isset($bundles['media']['processed_audio'])) {
    // This is a little bit bad, but this code seems to fire when the module is
    // being installed before the bundle is installed. Hence...
    return;
  }

  $bundles['media']['processed_audio']['class'] = ProcessedAudio::class;
}
