<?php

/**
 * @file
 * Sermon Audio hook implementations.
 */

declare (strict_types = 1);

use Drupal\Component\Utility\Html;
use Drupal\file\FileInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function sermon_audio_preprocess_file_link(array &$variables) : void {
  if (!empty($variables['sermon_audio_suppress_link'])) {
    $file = $variables['file'];
    if (!($file instanceof FileInterface)) {
      throw new \RuntimeException('Invalid theme hook variables.');
    }
    // In this case, we don't want to show an actual link to the file. Hence,
    // override the "link" variable with  the sanitized plain-text filename (it
    // should be sanitized by Twig automatically, but we do so here just in case
    // the template is changed later).
    $variables['link'] = Html::escape($file->getFilename());
  }
}
