<?php

/**
 * @file
 * Sermon Audio hook implementations.
 */

declare (strict_types = 1);

use Drupal\Component\Utility\Html;
use Drupal\file\FileInterface;

/**
 * Implements hook_theme_registry_alter().
 */
function sermon_audio_theme_registry_alter(array &$registry) : void {
  // Add a "sermon_audio_suppress_link" variable to the set of "file_link" theme
  // hook variables.
  if (!empty($registry['file_link'])) {
    $registry['file_link']['variables']['sermon_audio_suppress_link'] = NULL;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sermon_audio_preprocess_file_link(array &$variables) : void {
  if (!empty($variables['sermon_audio_suppress_link'])) {
    $file = $variables['file'];
    if (!($file instanceof FileInterface)) {
      throw new \RuntimeException('Invalid theme hook variables.');
    }
    // In this case, we don't want to show an actual link to the file. Hence,
    // override the "link" variable with  the sanitized plain-text filename (it
    // should be sanitized by Twig automatically, but we do so here just in case
    // the template is changed later).
    $variables['link'] = Html::escape($file->getFilename());
  }
}
