sermon_audio.settings:
  type: config_object
  label: 'Sermon Audio Settings'
  mapping:
    aws_credentials_file_path:
      type: string
      label: 'Full path to JSON file where AWS credentials are stored, if applicable (else leave empty)'
    site_token_file_path:
      type: string
      label: 'Full path to text file where site token (controlling access to announcement routes) is stored'
    audio_s3_aws_region:
      type: string
      label: 'AWS region where processed/unprocessed audio S3 bucket resides'
    audio_bucket_name:
      type: string
      label: 'Name of AWS S3 bucket where processed and unprocessed audio is stored'
    unprocessed_audio_uri_prefix:
      type: string
      label: 'Prefix, including scheme, for unprocessed audio file URIs'
    processed_audio_uri_prefix:
      type: string
      label: 'Prefix, including scheme, for newly processed audio file URIs. This is ignored in debug mode.'
    processed_audio_key_prefix:
      type: string
      label: 'S3 prefix of keys for processed audio'
    job_submission_endpoint_aws_region:
      type: string
      label: 'AWS region where processing job submission endpoint resides'
    job_submission_endpoint:
      type: string
      label: 'Audio processing job submission AWS HTTP endpoint'
    transcription_job_results_endpoint_aws_region:
      type: string
      label: 'AWS region where transcription job results endpoint resides'
    transcription_job_results_endpoint:
      type: string
      label: 'Transcription job results AWS HTTP endpoint'
    transcription_s3_aws_region:
      type: string
      label: 'AWS region where audio transcription S3 bucket resides'
    transcription_bucket_name:
      type: string
      label: 'Name of AWS S3 bucket where output transcription XML files are stored'
    transcription_key_prefix:
      type: string
      label: 'S3 prefix of keys for output transcription XML files'
    cleaning_job_results_endpoint_aws_region:
      type: string
      label: 'AWS region where audio cleaning job results endpoint resides'
    cleaning_job_results_endpoint:
      type: string
      label: 'Audio cleaning job results AWS HTTP endpoint'
    debug_mode:
      type: boolean
      label: >-
        Whether to enable "debug mode": when enabled, the processed audio field
        will simply be made the same as the unprocessed audio field when
        \Drupal\sermon_audio\Entity\SermonAudio::refreshProcessedAudio() is
        called. No actual audio processing or AWS API calls take place if this
        mode is enabled.
    connect_timeout:
      type: integer
      label: 'Timeout in seconds when attempting to connect to a server while making AWS calls'
    endpoint_timeout:
      type: integer
      label: 'Total timeout in seconds when making requests to custom AWS HTTP endpoints'
