sermon_audio.settings:
  type: config_object
  label: 'Sermon Audio Settings'
  mapping:
    aws_credentials_file_path:
      type: string
      label: 'Full path to JSON file where AWS credentials are stored, if applicable (else leave empty)'
    audio_s3_aws_region:
      type: string
      label: 'AWS region wherein S3 audio files reside'
    jobs_db_aws_region:
      type: string
      label: 'AWS region wherein DynamoDB audio processing jobs table resides'
    jobs_table_name:
      type: string
      label: 'Name of AWS DynamoDB audio processing jobs table'
    audio_bucket_name:
      type: string
      label: 'Name of AWS S3 bucket where processed and unprocessed audio is stored'
    unprocessed_audio_uri_prefix:
      type: string
      label: 'Prefix, including scheme, for unprocessed audio file URIs'
    processed_audio_uri_prefix:
      type: string
      label: 'Prefix, including scheme, for newly processed audio file URIs. This is ignored in debug mode.'
    processed_audio_key_prefix:
      type: string
      label: 'S3 prefix newly processed audio keys'
    debug_mode:
      type: boolean
      label: >-
        Whether to enable "debug mode": when enabled, the processed audio field
        will simply be made the same as the unprocessed audio field when
        \Drupal\sermon_audio\Entity\SermonAudio::refreshProcessedAudio() is
        called. No actual audio processing or AWS API calls take place if this
        mode is enabled.
    connect_timeout:
      type: integer
      label: 'Timeout in seconds when attempting to connect to a server while making AWS calls'
    dynamodb_timeout:
      type: integer
      label: 'Timeout in seconds when making AWS DynamoDB requests (whose responses should return relatively quickly)'
