sermon_audio.settings:
  type: config_object
  label: 'Sermon Audio Settings'
  mapping:
    aws_credentials_file_path:
      type: string
      label: 'Full path to JSON file where AWS credentials are stored, if applicable (else leave empty)'
    jobs_db_aws_region:
      type: string
      label: 'AWS region wherein DynamoDB audio processing jobs table resides'
    jobs_table_name:
      type: string
      label: 'Name of AWS DynamoDB audio processing jobs table'
    unprocessed_audio_uri_prefix:
      type: string
      label: 'Prefix, including scheme, for unprocessed audio file URIs'
    processed_audio_uri_prefix:
      type: string
      label: 'Prefix, including scheme, for processed audio file URIs'
